config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :pages
  resources :posts do 
    resources :comments
  end
  resources :sessions, only: [:new, :create]

  get "/logout", to: "sessions#destroy"
  get "/about", to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  broadcasts_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :title
    has_rich_text :content
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_presence_of :email
    validates_uniqueness_of :email

    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include AuthenticateUserConcern
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :set_post

    def create
        comment = @post.comments.create! params.required(:comment).permit(:content)
        CommentsMailer.submitted(comment).deliver_later
        redirect_to @post
    end

    private 
    
    def set_post
        @post = Post.find(params[:post_id])
    end
end

app/controllers/concerns/authenticate_user_concern.rb
module AuthenticateUserConcern

    extend ActiveSupport::Concern

    def authenticate_user
        
        # byebug
        token = session[:token]
        
        if token
            secret_key = Rails.application.secret_key_base
            
            decoded_token = JWT.decode(token, secret_key)[0]

            @user = User.find(decoded_token["user_id"])

        else
            redirect_to new_session_path
        end

        
        # authorization_header = request.headers[:authorization]
        # if authorization_header
        # else
        #     render status: :unauthorized
        # end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def about
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user, only: [:index]

  # GET /posts or /posts.json
  def index
    @posts = @user.posts
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create

        user= User.find_by(email: session_params[:email])

        if user && user.authenticate(session_params[:password])

            secret_key = Rails.application.secret_key_base
            token = JWT.encode({user_id: user.id}, secret_key)
            session[:token] = token
            authenticate_user
            redirect_to @user

        else

            flash[:notice] = "Unable to verify email or password"
            redirect_to new_session_path

        end
    end

    def destroy
        session[:token] = nil
        flash[:notice] = "You have been signed out successfully!"
        redirect_to new_session_path
    end

    private

    def session_params
        session_params = params.permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user, only: [:show, :edit, :update]

  # GET /users/1 or /users/1.json
  def show
    @posts = @user.posts
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit

  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password_digest, :profile_picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
    <%= comment.content %>
    - <%= time_tag comment.created_at, "data-local": "time-ago" %>
</div>

app/views/comments/_new.html.erb
<%= form_with model: [ post, Comment.new ] do |form| %>
    Your comment: <br>
    <%= form.text_area :content, size: "20x5" %>
    <%= form.submit %>    
<% end %>
    

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
  </head>

  <body>

    <header>
      <nav>

        <% if @user %>
          <div id="nav-buttons">
            <%= link_to  "Posts", posts_path, class: "navbar-item" %>
            <%= link_to  "Sign Out", "/logout", class: "navbar-item" %>
          </div>
          <%= content_tag :h1, flash[:notice] %>
        <% else %>
          <div id="nav-buttons">
            <%= link_to  "About", "/about" %>
            <%= link_to  "Login", new_session_path %>
          </div>
          <%= content_tag :h1, flash[:notice] %>
        <% end %>
      </nav>

    </header>

    <%= yield %>

  </body>

  <footer>
    <%= button_to "Destroy this user", @user, method: :delete %>
  </footer>
</html>

app/views/pages/about.html.erb
<h2>About</h2>

app/views/posts/_comments.html.erb
<h2> Comments </h2>

<div id="comments">
    <%= render post.comments %>
</div>

<%= render "comments/new", post: post %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= post.content %>
  </p>
  <p>
    <strong>Posted:</strong>
    <%= time_tag post.created_at, "data-local": "time-ago" %>
  </p>
  <p>
    <strong><%= pluralize post.comments.count, "comment" %></strong>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<%= turbo_stream_from @post %>

<p style="color: green"><%= notice %></p>

<%= render @post %>
<%= render "posts/comments", post: @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password_digest, style: "display: block" %>
    <%= form.text_field :password_digest %>
  </div>

  <div>
    <%= form.label :profile_picture, style: "display: block" %>
    <%= form.text_field :profile_picture %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<h2>User Show</h2>
  <p style="color: green"><%= notice %></p>

  <div class="conatiners">
  
    <div class="container">
      <%= render @user %>
    </div>

    <div class="container">
      <%= link_to "New post", new_post_path %>
      <div>
        <% @posts.each do |post| %>
          <%= render post %>
          <p>
            <%= link_to "Show this post", post %>
          </p>
        <% end %>
      </div>
    </div>
  </div>